feat: lastEventResolver
kodadot/snek pull request #42
Opened 2022-07-26 14:18 UTC by zhengow

This is for [#3570](https://github.com/kodadot/nft-gallery/issues/3570) and [#3571](https://github.com/kodadot/nft-gallery/issues/3571), query latest event with condition `interaction`.
The same implement as rmrk, only logic about `passionList` remove.

2022-07-26 14:24 UTC, zhengow commented
I want to give a picture about query data, but it seems no event happen.

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/38389586/181030792-86d4944a-8581-44db-8566-6ffb332c5317.png">
<img width="922" alt="image" src="https://user-images.githubusercontent.com/38389586/181030851-fcbeb57b-20f4-4771-82d2-e8216cceb45a.png">

2022-07-27 18:11 UTC, vikiival approved these changes

2022-07-27 18:11 UTC, vikiival commented
Basically copy-paste from kodadot/magick

2022-07-27 18:12 UTC, vikiival commented
Oh you tested that against the latest main?

2022-07-27 20:34 UTC, zhengow commented
> Oh you tested that against the latest main?

Now I try the latest main, however it seems there is error( is this my bug or not?).
My step:
1. just up
2. just codegen
3. just reset
4. just process
5. just serve

<img width="1529" alt="image" src="https://user-images.githubusercontent.com/38389586/181366828-06e9b536-8f57-40a0-b5f2-93ea94f9c5e9.png">

```
npm run build

> @kodadot1/snek@0.0.1-rc.0 build
> rm -rf lib && tsc

node -r dotenv/config lib/processor.js
●  note      Welcome to the Processor! https://basilisk-rococo.play.hydration.cloud/v1/graphql
Prometheus metrics are served at port 63813
☐  pending   [COLECTTION++]: 12153
.isLatest, .asLatest properties are deprecated, if you believe this is a mistake, please leave a comment at https://github.com/subsquid/squid/issues/9
⬤  debug     collection: {
  "caller": "bXj4uMHTrBtVfmVMDpQ1AyUUNbnvLaRPcBDVTeLffL2h2U3KE",
  "blockNumber": "12153",
  "timestamp": "2022-05-05T08:09:12.202Z",
  "id": "1",
  "metadata": "",
  "type": "LiquidityMining"
}
⬤  debug     metadata: ipfs://ipfs/bafkreiazeqysfmeuzqcnjp6rijxfu5h7sj3t4h2rxehi7rlyegzfy7lxeq
…  watching  [IPFS] 200 ipfs://ipfs/bafkreiazeqysfmeuzqcnjp6rijxfu5h7sj3t4h2rxehi7rlyegzfy7lxeq
✔  success   [COLLECTION] 1
☐  pending   [COLECTTION++]: 497726
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, assert_1.default)(this.isV48)

    at NftClassCreatedEvent.get asV48 [as asV48] (/Users/brownzheng/Documents/UGit/snek1/lib/types/events.js:220:30)
    at NftClassCreatedEvent.get asLatest [as asLatest] (/Users/brownzheng/Documents/UGit/snek1/lib/types/events.js:229:21)
    at getCreateCollectionEvent (/Users/brownzheng/Documents/UGit/snek1/lib/mappings/utils/getters.js:17:60)
    at unwrap (/Users/brownzheng/Documents/UGit/snek1/lib/mappings/utils/extract.js:18:23)
    at handleCollectionCreate (/Users/brownzheng/Documents/UGit/snek1/lib/mappings/index.js:63:40)
    at /Users/brownzheng/Documents/UGit/snek1/node_modules/@subsquid/substrate-processor/lib/processor.js:285:35
    at /Users/brownzheng/Documents/UGit/snek1/node_modules/@subsquid/substrate-processor/lib/db.js:69:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
error: Recipe `process` failed on line 4 with exit code 1
```

2022-07-28 18:04 UTC, zhengow commented
I try the latest main branch, the same behavior, too.

2022-08-01 11:18 UTC, vikiival commented
Plese try to pull the latest main

2022-08-03 10:01 UTC, yangwao commented
is this good to go?

2022-08-03 13:22 UTC, vikiival requested changes
<img width="1366" alt="Screenshot 2022-08-03 at 15 22 06" src="https://user-images.githubusercontent.com/22471030/182618533-3945cd59-efe8-426b-afa6-8288b0c7fc01.png">

2022-08-03 13:29 UTC, merged

2022-08-03 13:30 UTC, vikiival commented
🦑 Releasing the squid at git@github.com:kodadot/snek.git#5cd19f51b705e0812492ad683997d39a0f657bdd